#!/bin/bash
set -euo pipefail

(( EUID == 0 )) || { echo This script needs to be run as root; exit 1; }

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PACKAGES=(
    adguardhome
    base
    btrfs-progs
    cachyos-keyring
    cachyos-mirrorlist
    cachyos-v3-mirrorlist
    foot
    git
    grimblast-git
    hyprland
    hyprpaper
    hyprpicker
    iptables-nft
    iwd
    librewolf-bin
    neovim
    noto-fonts
    pass-otp
    pipewire-jack
    pipewire-pulse
    sbctl
    signal-desktop
    ttf-nerd-fonts-symbols
    wireguard-tools
    wl-clipboard
)

export SERVICES=(
    adguardhome.service
    getty@.service
    iwd.service
    nftables.service
    misc.service
    systemd-timesyncd.service
    wireguard.service
)

export TIMERS=(
    btrfs-scrub@-.timer
    fstrim.timer
)

configuration() {
    find "$SCRIPTDIR"/rootfs -type f | while read -r src; do
        ARGS=(-Dm644)
        [[ "$src" =~ AdGuardHome ]] && ARGS=(-Dm600 -o nobody -g nobody)
        [[ "$src" =~ /home/user ]] && ARGS=(-Dm644 -o user -g user)
        [[ "$src" =~ /usr/local/bin ]] && ARGS=(-Dm755)
        cmp -s "$src" /"${src#"$SCRIPTDIR"/rootfs/}" || install "${ARGS[@]}" "$src" /"${src#"$SCRIPTDIR"/rootfs/}"
    done

    pacman -S --noconfirm --needed "${PACKAGES[@]}"

    if ! [[ $(pacman -Q openrgb | awk '{print $2}') = '1.0rc1-2' ]]; then
        (cd /tmp # Openrgb is completely broken for me after this version
        curl -OJ https://archive.archlinux.org/repos/2025/08/31/extra/os/x86_64/openrgb-1.0rc1-2-x86_64.pkg.tar.zst
        pacman -U --noconfirm openrgb*.zst)
    fi

    diff --color=always <(pacman -Qqe) <(printf '%s\n' "${PACKAGES[@]}") || :

    sed -i "s|^;.*cookie-file.*|cookie-file = /tmp/.pulse-cookie|" /etc/pulse/client.conf # Fix Steam creating ~/.pulse-cookie
    sed -i 's|which|command -v|' /usr/lib/password-store/extensions/otp.bash # Fix `which` not found by pass otp

    for svc in "${SERVICES[@]}"; do
        systemctl is-enabled -q "$svc" || systemctl enable $NOW "$svc"
    done

    for svc in $(systemctl list-unit-files --type=service --state=enabled --no-legend | awk '{print $1}'); do
        [[ "${SERVICES[*]}" =~ $svc ]] || systemctl disable $NOW "$svc"
    done

    systemctl enable "${TIMERS[@]}"
    systemctl mask systemd-boot-random-seed.service

    for d in /home/user/.{cache,local}; do
        [[ $(readlink "$d") == /tmp ]] || { ln -sfn /tmp "$d" && chown user:user "$d"; }
    done

    mkinitcpio -P || :

    if sbctl status | grep -q "Setup Mode:.*Enabled" && [[ -e /dev/tpm0 ]]; then
        sbctl create-keys
        sbctl enroll-keys --tpm-eventlog
        sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
    else
        echo Skipping Secure Boot setup as it is not in Setup Mode or no TPM detected
    fi
}

if [[ -d /run/archiso ]]; then
    : "$DISK:?" "$PASS:?"

    echo -e "You probably shouldn't be running this if you aren't Zenixark.\nType 'IK' to continue to disk wiping: "
    read -r IK
    [[ "$IK" == IK ]] || { echo "You didn't confirm you knew"; exit 1; }

    umount -R /mnt &> /dev/null || :
    cryptsetup close cryptroot &> /dev/null || :

    [[ "$DISK" =~ nvme ]] && { nvme id-ns -H /dev/"$DISK" | grep -q "1.*4096"; } && nvme format --lbaf=1 --force /dev/"$DISK"

    sgdisk --zap-all /dev/"$DISK"
    sgdisk -g /dev/"$DISK"
    sgdisk -I -n 1:0:+512M -t 1:ef00 -c 1:bootfs /dev/"$DISK"
    sgdisk -I -n 2:0:0 -t 2:8300 -c 2:rootfs /dev/"$DISK"

    [[ "$DISK" =~ [0-9]$ ]] && DISK="$DISK"p

    mkfs.fat -F 32 /dev/"$DISK"1

    echo "$PASS" | cryptsetup -q luksFormat -h sha512 -i 5000 -s 512 /dev/"$DISK"2
    echo "$PASS" | cryptsetup open /dev/"$DISK"2 cryptroot

    mkfs.btrfs -f /dev/mapper/cryptroot

    mount /dev/mapper/cryptroot /mnt
    btrfs su cr /mnt/@
    btrfs su cr /mnt/@home
    btrfs su cr /mnt/@var_log
    btrfs su cr /mnt/@var_cache
    btrfs su cr /mnt/@var_lib_libvirt_images
    chattr +C /mnt/@var_{log,cache,lib_libvirt_images}
    umount /mnt

    mount -o defaults,compress-force=zstd,noatime,subvol=@ /dev/mapper/cryptroot /mnt
    mkdir -p /mnt/{boot,home,var/{log,cache,lib/libvirt/images}}
    mount -o defaults,nodev,nosuid,noexec,umask=0077 /dev/"$DISK"1 /mnt/boot
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,subvol=@home /dev/mapper/cryptroot /mnt/home
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_log /dev/mapper/cryptroot /mnt/var/log
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_cache /dev/mapper/cryptroot /mnt/var/cache
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_lib_libvirt_images /dev/mapper/cryptroot /mnt/var/lib/libvirt/images

    reflector -c US -p https -a 12 -l 20 -f 5 --sort rate --save /etc/pacman.d/mirrorlist
    sed -i "s/^#\(ParallelDownloads = 5\)/\1/" /etc/pacman.conf

    curl https://mirror.cachyos.org/cachyos-repo.tar.xz | tar xJvf -
    (cd cachyos-repo && ./cachyos-repo.sh)

    pacstrap /mnt "${PACKAGES[@]}"

    genfstab -U /mnt >> /mnt/etc/fstab

    useradd -R /mnt -m user
    chpasswd -R /mnt <<< "root:$PASS"

    cp -r "$SCRIPTDIR" /mnt/home/user/.zenixarch/

    arch-chroot /mnt NOW='' SCRIPTDIR=/home/user/.zenixarch bash -e << CHROOT
        $(declare -f configuration)

        echo LANG=en_US.UTF-8 > /etc/locale.conf
        echo en_US.UTF-8 UTF-8 > /etc/locale.gen
        locale-gen

        ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
        hwclock --systohc

        pacman -S --noconfirm base-devel
        echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/00_user

        (cd \$SCRIPTDIR/kernel
        sed -i "s|UUID=.*:cryptroot|UUID=$(blkid -s UUID -o value "$(cryptsetup status cryptroot | awk '/device:/ {print $2}')"):cryptroot|" config
        sudo -u user makepkg -si --noconfirm

        pacman -Rcns --noconfirm base-devel
        rm -rf /boot/* /etc/sudoers.d src pkg *.{patch,xz,run})
        mkdir -p /boot/EFI/BOOT

        configuration
CHROOT
else
    NOW=--now configuration
fi

echo Done
