#!/bin/bash
set -euo pipefail

(( EUID == 0 )) || { echo "This script needs to be run as root"; exit 1; }

configuration() {
    mapfile -t files < <(find /home/user/.zenixarch/{etc,home,var} -type f)
    for src in "${files[@]}"; do
        cmp -s "$src" "/${src#/home/user/.zenixarch/}" || install -Dm644 "$src" "/${src#/home/user/.zenixarch/}"
    done

    sed -i "s|\${UUID}|$(blkid -s UUID -o value "$(cryptsetup status cryptroot | awk '/device:/ {print $2}')")|g" /etc/kernel/cmdline

    pacman -S --noconfirm --needed - < /home/user/.zenixarch/zarchpackages.txt

    ping -c 1 zenixark.com &>/dev/null && curl https://zenixark.com/api/v1/repos/zenixark/firefox-hardening/raw/mkuserjs > /usr/local/bin/mkuserjs && chmod +x /usr/local/bin/mkuserjs && mkuserjs

    ## The .local symlink is just an experiment, I might revert it later but for the time being I have no purpose for its existence
    ln -sfn /tmp /home/user/.cache
    ln -sfn /tmp /home/user/.local

    chmod 600 /etc/doas.conf /var/lib/private/adguardhome/AdGuardHome.yaml
    chown -R nobody:nobody /var/lib/private/adguardhome
    chown -R user:user /home/user

    mapfile -t services < /home/user/.zenixarch/zarchservices.txt
    for svc in "${services[@]}"; do
        [[ -n "$svc" ]] || continue
        systemctl enable $NOW "$svc"
    done

    for svc in $(systemctl list-unit-files --type=service --state=enabled --no-legend | awk '{print $1}'); do
        [[ "${services[*]}" != "$svc" ]] || systemctl disable $NOW "$svc"
    done

    systemctl enable {fstrim,btrfs-scrub@-}.timer

    systemctl mask systemd-boot-random-seed.service

    for mod in /home/user/.zenixarch/zarchmodules/*; do "$mod"; done

    mkinitcpio -p linux

    ## I use --tpm-eventlog because otherwise my GPU's GOP driver doesn't get initialized leaving me with no boot video until the gpu drivers load which then it's just a software rendered framebuffer
    ## This does prevent me from running the command inside a live ISO though... for whatever reason the TPM2 isnt detected in a live environment. This just means that zarchinstall can be ran again post-reboot to set it up assuming Setup Mode is still enabled.
    if sbctl status | grep -q "Setup Mode:.*Enabled"; then
        sbctl create-keys
        sbctl enroll-keys --tpm-eventlog
        sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
    else
        echo -e "\e[33mSkipping Secure Boot as it is not in Setup Mode\e[0m"
    fi
}

if [[ -d /run/archiso ]]; then
    : "$DISK:?" "$PASS:?"

    read -rp $'\e[31mThis will wipe every little thing on your disk and reformat\n\e[31mAlso, you should know EVERYTHING this does before running it because it makes a LOT of assumptions\n\e[31mType "IK" to continue: \e[0m' CONFIRM
    [[ "$CONFIRM" != "IK" ]] && echo -e "\e[31mError: You didn't confirm you knew\e[0m" && exit 1

    mountpoint -q /mnt && umount -R /mnt && cryptsetup close cryptroot

    nvme id-ns -H "/dev/$DISK" | grep -q "LBA Format  1.*Data Size: 4096" && nvme format --lbaf=1 --force "/dev/$DISK"

    sgdisk --zap-all "/dev/$DISK"
    sgdisk -g "/dev/$DISK"
    sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "/dev/$DISK"
    sgdisk -n 2:0:0 -t 2:8300 -c 2:"Linux filesystem" "/dev/$DISK"

    [[ "$DISK" =~ [0-9]$ ]] && DISK="${DISK}p"

    mkfs.fat -F 32 "/dev/${DISK}1"

    echo "$PASS" | cryptsetup -q luksFormat -h sha512 -i 5000 -s 512 "/dev/${DISK}2"
    echo "$PASS" | cryptsetup open "/dev/${DISK}2" cryptroot

    mkfs.btrfs -f /dev/mapper/cryptroot

    mount /dev/mapper/cryptroot /mnt
    btrfs su cr /mnt/@
    btrfs su cr /mnt/@home
    btrfs su cr /mnt/@var_log
    btrfs su cr /mnt/@var_cache
    btrfs su cr /mnt/@var_lib_libvirt_images
    chattr +C /mnt/@var_{log,cache,lib_libvirt_images}
    umount /mnt

    mount -o defaults,compress-force=zstd,noatime,subvol=@ /dev/mapper/cryptroot /mnt
    mkdir -p /mnt/{boot,home,var/{log,cache,lib/libvirt/images}}
    mount -o defaults,nodev,nosuid,noexec,umask=0077 "/dev/${DISK}1" /mnt/boot
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,subvol=@home /dev/mapper/cryptroot /mnt/home
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_log /dev/mapper/cryptroot /mnt/var/log
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_cache /dev/mapper/cryptroot /mnt/var/cache
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_lib_libvirt_images /dev/mapper/cryptroot /mnt/var/lib/libvirt/images

    reflector -c US -p https -a 12 -l 20 -f 5 --sort rate --save /etc/pacman.d/mirrorlist
    sed -i 's/^#\(ParallelDownloads = 5\)/\1/' /etc/pacman.conf
    pacman -Sy --noconfirm archlinux-keyring

    pacstrap /mnt - < "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/zarchpackages.txt

    mv /mnt/boot/vmlinuz-linux /mnt/usr/lib/modules/vmlinuz
    rm -rf /mnt/boot/*
    mkdir -p /mnt/boot/EFI/BOOT

    genfstab -U /mnt >> /mnt/etc/fstab

    cp -r "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" /mnt/.zenixarch/

    arch-chroot /mnt /bin/bash -e <<CHROOT
    export NOW=""
    $(declare -f configuration)

    ln -sf "/usr/share/zoneinfo/America/New_York" /etc/localtime
    hwclock --systohc

    sed -i 's/^#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    locale-gen

    useradd -m user
    chpasswd <<< "root:$PASS"$'\n'"user:$PASS"
    passwd --lock root

    mv /.zenixarch /home/user

    configuration
CHROOT

else
    export NOW="--now"
    configuration
fi

echo -e "\e[32mDone!\e[0m"
