#!/bin/bash
set -euo pipefail
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

(( EUID == 0 )) || { echo "This script needs to be run as root"; exit 1; }

configuration() {
    find "$SCRIPTDIR"/configs -type f | while read -r src; do
        if [[ "$src" =~ adguardhome.yaml ]]; then
            cmp -s "$src" /var/lib/private/adguardhome/AdGuardHome.yaml || install -Dm600 -o nobody -g nobody "$src" /var/lib/private/adguardhome/AdGuardHome.yaml
        else
            cmp -s "$src" /etc/"${src#"$SCRIPTDIR"/configs/}" || install -Dm644 "$src" /etc/"${src#"$SCRIPTDIR"/configs/}"
        fi
    done

    find "$SCRIPTDIR"/dotfiles -type f | while read -r src; do
        cmp -s "$src" /home/user/"${src#"$SCRIPTDIR"/dotfiles/}" || install -Dm644 "$src" /home/user/"${src#"$SCRIPTDIR"/dotfiles/}"
    done

    sed -i "s|\${UUID}|$(blkid -s UUID -o value "$(cryptsetup status cryptroot | awk '/device:/ {print $2}')")|" /etc/kernel/cmdline

    chmod 600 /etc/doas.conf

    pacman -Syu --needed - < "$SCRIPTDIR"/packages.txt

    while read -r svc; do systemctl enable $NOW "$svc"; done < "$SCRIPTDIR"/services.txt
    for svc in $(systemctl list-unit-files --type=service --state=enabled --no-legend | awk '{print $1}'); do
        grep -qx "$svc" "$SCRIPTDIR"/services.txt || systemctl disable $NOW "$svc"
    done

    systemctl enable {fstrim,btrfs-scrub@-}.timer
    systemctl mask systemd-boot-random-seed.service

    for ex in "$SCRIPTDIR"/extras/*; do "$ex"; done

    ln -sfn /tmp /home/user/.cache
    ln -sfn /tmp /home/user/.local

    chown -R user:user /home/user

    mkinitcpio -p linux-cachyos-bore-lto

    if sbctl status | grep -q "Setup Mode:.*Enabled"; then
        sbctl create-keys
        sbctl enroll-keys --tpm-eventlog
        sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
    else
        echo -e "\e[33mSkipping Secure Boot as it is not in Setup Mode\e[0m"
    fi
}

if [[ -d /run/archiso ]]; then
    : "$DISK:?" "$PASS:?"

    read -rp $'\e[31mThis will wipe every little thing on your disk and reformat\n\e[31mAlso, you should know EVERYTHING this does before running it because it makes a lot of assumptions\n\e[31mType "IK" to continue: \e[0m' CONFIRM
    [[ "$CONFIRM" != "IK" ]] && echo -e "\e[31mYou didn't confirm you knew\e[0m" && exit 1

    umount -R /mnt &>/dev/null || true && umount -R /mnt/* &>/dev/null || true && cryptsetup close cryptroot &>/dev/null || true

    [[ "$DISK" =~ nvme ]] && nvme id-ns -H "/dev/$DISK" | grep -q "LBA Format  1.*Data Size: 4096" && nvme format --lbaf=1 --force "/dev/$DISK"

    sgdisk --zap-all "/dev/$DISK"
    sgdisk -g "/dev/$DISK"
    sgdisk -I -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" "/dev/$DISK"
    sgdisk -I -n 2:0:0 -t 2:8300 -c 2:"Linux filesystem" "/dev/$DISK"

    [[ "$DISK" =~ [0-9]$ ]] && DISK="${DISK}p"

    mkfs.fat -F 32 "/dev/${DISK}1"

    echo "$PASS" | cryptsetup -q luksFormat -h sha512 -i 5000 -s 512 "/dev/${DISK}2"
    echo "$PASS" | cryptsetup open "/dev/${DISK}2" cryptroot

    mkfs.btrfs -f /dev/mapper/cryptroot

    mount /dev/mapper/cryptroot /mnt
    btrfs su cr /mnt/@
    btrfs su cr /mnt/@home
    btrfs su cr /mnt/@var_log
    btrfs su cr /mnt/@var_cache
    btrfs su cr /mnt/@var_lib_libvirt_images
    chattr +C /mnt/@var_{log,cache,lib_libvirt_images}
    umount /mnt

    mount -o defaults,compress-force=zstd,noatime,subvol=@ /dev/mapper/cryptroot /mnt
    mkdir -p /mnt/{boot,home,var/{log,cache,lib/libvirt/images}}
    mount -o defaults,nodev,nosuid,noexec,umask=0077 "/dev/${DISK}1" /mnt/boot
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,subvol=@home /dev/mapper/cryptroot /mnt/home
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_log /dev/mapper/cryptroot /mnt/var/log
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_cache /dev/mapper/cryptroot /mnt/var/cache
    mount -o defaults,compress-force=zstd,noatime,nodev,nosuid,noexec,subvol=@var_lib_libvirt_images /dev/mapper/cryptroot /mnt/var/lib/libvirt/images

    reflector -c US -p https -a 12 -l 20 -f 5 --sort rate --save /etc/pacman.d/mirrorlist
    sed -i 's/^#\(ParallelDownloads = 5\)/\1/' /etc/pacman.conf

    curl https://mirror.cachyos.org/cachyos-repo.tar.xz > cachyos-repo.tar.xz
    tar xvf cachyos-repo.tar.xz
    (cd cachyos-repo && ./cachyos-repo.sh)

    pacstrap /mnt - < "$SCRIPTDIR"/packages.txt

    mv /mnt/boot/vmlinuz-linux /mnt/usr/lib/modules/vmlinuz
    rm -rf /mnt/boot/*
    mkdir -p /mnt/boot/EFI/BOOT

    genfstab -U /mnt >> /mnt/etc/fstab

    cp -r "$SCRIPTDIR" /mnt/.zenixarch/

    arch-chroot /mnt bash -e << CHROOT
    export NOW="" SCRIPTDIR="/home/user/.zenixarch"
    $(declare -f configuration)

    ln -sf "/usr/share/zoneinfo/America/New_York" /etc/localtime
    hwclock --systohc

    sed -i 's/^#\(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
    locale-gen

    useradd -m user
    chpasswd <<< "root:$PASS"$'\n'"user:$PASS"
    passwd --lock root

    mv /.zenixarch /home/user

    configuration
CHROOT

else
    export NOW="--now" SCRIPTDIR="$SCRIPTDIR"
    configuration
fi

echo -e "\e[32mDone!\e[0m"
